spring:
  profiles:
    default: local

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}

google:
  calendar:
    id: ${GOOGLE_CALENDAR_ID}
    credentials-path: ${GOOGLE_CREDENTIALS_PATH:classpath:google-credentials.json}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
